const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);
const on = (channel) => (cb) => ipcRenderer.on(channel, (_e, payload) => cb(payload));

contextBridge.exposeInMainWorld('api', {
  getState: () => invoke('state:get'),
  saveSettings: (patch) => invoke('settings:save', patch),
  pickOutputDir: () => invoke('settings:pickDir'),
  openOutputDir: () => invoke('app:openOutputDir'),
  testNotification: () => invoke('notify:test'),
  openLink: (url) => invoke('link:open', url),

  setProvider: (id, cfg) => invoke('provider:set', id, cfg),
  listModels: (id, refresh) => invoke('provider:models', id, refresh),

  saveWriter: (w) => invoke('writer:save', w),
  deleteWriter: (id) => invoke('writer:delete', id),
  runWriter: (id, topic) => invoke('writer:run', id, topic),
  pickKnowledgeFiles: () => invoke('writer:pickFiles'),

  saveSchedule: (s) => invoke('schedule:save', s),
  deleteSchedule: (id) => invoke('schedule:delete', id),
  toggleSchedule: (id, enabled) => invoke('schedule:toggle', id, enabled),
  previewSchedule: (s) => invoke('schedule:preview', s),

  subscriptionStatus: () => invoke('sub:status'),
  subscriptionLogin: () => invoke('sub:login'),
  installCodex: () => invoke('sub:install'),
  unlock: (pw) => invoke('lock:unlock', pw),
  setPassword: (current, next) => invoke('lock:set', current, next),
  removePassword: (current) => invoke('lock:remove', current),
  skipPasswordSetup: () => invoke('lock:skipSetup'),
  lockNow: () => invoke('lock:now'),
  resetPassword: () => invoke('lock:reset'),
  subscriptionLogout: () => invoke('sub:logout'),

  wpConnect: (url, siteId) => invoke('site:wpConnect', url, siteId),
  saveSiteManual: (site) => invoke('site:saveManual', site),
  renameSite: (id, name) => invoke('site:rename', id, name),
  testSite: (id) => invoke('site:test', id),
  deleteSite: (id) => invoke('site:delete', id),
  publishArticle: (id, siteId, opts) => invoke('article:publish', id, siteId, opts),
  linkOlderPosts: (id, mode) => invoke('article:linkOlder', id, mode),
  setImages: (cfg) => invoke('images:set', cfg),
  googleUserSignIn: (id, secret, features) => invoke('guser:signIn', id, secret, features),
  googleUserDisconnect: () => invoke('guser:disconnect'),
  gbpLocations: () => invoke('guser:gbpLocations'),
  setSiteGbp: (id, cfg) => invoke('site:setGbp', id, cfg),
  gbpCheckNow: (siteId) => invoke('gbp:checkNow', siteId),
  saveTask: (t) => invoke('task:save', t),
  setTaskStatus: (id, status) => invoke('task:status', id, status),
  deleteTasks: (ids) => invoke('task:delete', ids),
  draftTaskReply: (id) => invoke('task:draftReply', id),
  runDigest: () => invoke('digest:run'),
  scanGmailNow: () => invoke('gmail:scanNow'),
  weeklyUpdateNow: (id) => invoke('client:weeklyNow', id),
  clientReportNow: (id, offset) => invoke('client:reportNow', id, offset),
  openReport: (id, fmt) => invoke('report:open', id, fmt),
  revealReport: (id) => invoke('report:reveal', id),
  exportAuditReport: (runId) => invoke('audit:export', runId),
  configureDistribution: (patch) => invoke('dist:configure', patch),
  bufferProfiles: () => invoke('dist:bufferProfiles'),
  mailchimpLists: () => invoke('dist:mailchimpLists'),
  shareArticle: (id) => invoke('article:share', id),
  newsletterNow: (id) => invoke('client:newsletterNow', id),
  setSeoConfig: (id, cfg) => invoke('seo:setConfig', id, cfg),
  checkRanks: (id) => invoke('seo:checkRanks', id),
  suggestKeywords: (id) => invoke('seo:suggestKeywords', id),
  checkIndexing: (id) => invoke('seo:checkIndexing', id),
  watchUrl: (id, url) => invoke('seo:watchUrl', id, url),
  removeWatch: (wid) => invoke('seo:removeWatch', wid),
  startTitleTests: (id) => invoke('seo:startTitleTests', id),
  planTopics: (id, count) => invoke('writer:planTopics', id, count),
  setWriterPlan: (id, plan) => invoke('writer:setPlan', id, plan),
  setWebdevConfig: (id, cfg) => invoke('webdev:setConfig', id, cfg),
  webdevCheck: (id, what) => invoke('webdev:check', id, what),
  runUpdates: (id, slugs) => invoke('webdev:runUpdates', id, slugs),
  setSiteMonitor: (id, cfg) => invoke('site:setMonitor', id, cfg),
  checkSiteNow: (id) => invoke('site:checkNow', id),
  setSiteClient: (id, clientId) => invoke('site:setClient', id, clientId),
  saveClient: (c) => invoke('client:save', c),
  deleteClient: (id) => invoke('client:delete', id),

  googleServiceAccount: () => invoke('google:serviceAccount'),
  googleOAuth: (id, secret) => invoke('google:oauth', id, secret),
  googleRefresh: () => invoke('google:refresh'),
  googleDisconnect: () => invoke('google:disconnect'),
  googlePsiKey: (key) => invoke('google:psiKey', key),
  setSiteGoogle: (id, g) => invoke('site:setGoogle', id, g),
  addUrlSite: (s) => invoke('site:addUrl', s),
  resumeSite: (id) => invoke('site:resume', id),
  setSitePace: (id, pace) => invoke('site:setPace', id, pace),
  saveConnector: (c) => invoke('connector:save', c),
  connectConnector: (id) => invoke('connector:connect', id),
  signOutConnector: (id) => invoke('connector:signOut', id),
  deleteConnector: (id) => invoke('connector:delete', id),
  setToolRisk: (id, tool, risk) => invoke('connector:setRisk', id, tool, risk),
  saveAuditJob: (j) => invoke('audit:saveJob', j),
  toggleAuditJob: (id, on) => invoke('audit:toggleJob', id, on),
  deleteAuditJob: (id) => invoke('audit:deleteJob', id),
  runAudit: (id) => invoke('audit:run', id),
  stopAudit: (runId) => invoke('audit:stop', runId),
  decideApproval: (id, approve) => invoke('audit:decide', id, approve),
  decideApprovals: (ids, approve) => invoke('audit:decideAll', ids, approve),
  revertChange: (id) => invoke('audit:revert', id),
  readAuditReport: (runId) => invoke('audit:readReport', runId),
  revealAuditReport: (runId) => invoke('audit:revealReport', runId),

  readArticle: (id) => invoke('article:read', id),
  deleteArticle: (id, removeFile) => invoke('article:delete', id, removeFile),
  revealArticle: (id) => invoke('article:reveal', id),
  openArticleFile: (id) => invoke('article:openFile', id),

  onState: on('state'),
  onOpenArticle: on('open-article'),
  onNavigate: on('navigate'),
  onToast: on('toast'),
  onNavigateTo: on('navigate-to'),
  onLoginUrl: on('login-url'),
  onCodexProgress: on('codex-progress')
});
